const ActionTypes = {
  SIMPLE_ACTION: 'SIMPLE_ACTION',
  SHOW_ACTIVITY_INDICATOR: 'SHOW_ACTIVITY_INDICATOR',
  HIDE_ACTIVITY_INDICATOR: 'HIDE_ACTIVITY_INDICATOR',
  GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
  GET_ALL_POSTS_FAILURE: 'GET_ALL_POSTS_FAILURE',
  CREATE_USER_POST_SUCCESS: 'CREATE_USER_POST_SUCCESS',
  GET_USER_POSTS_SUCCESS: 'GET_USER_POSTS_SUCCESS',
  GET_USER_POSTS_FAILURE: 'GET_USER_POSTS_FAILURE',
  UPVOTE_POST_SUCCESS: 'UPVOTE_POST_SUCCESS',
  UPVOTE_POST_FAILURE: 'UPVOTE_POST_FAILURE',
  DOWNVOTE_POST_SUCCESS: 'DOWNVOTE_POST_SUCCESS',
  DOWNVOTE_POST_FAILURE: 'DOWNVOTE_POST_FAILURE',
}

export default ActionTypes
